apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      name: client
      labels:
        name: web
    spec:
      containers:
        - name: client
          image: kman4you/multi-client
          ports:
            - containerPort: 3000
