version: "3"
services:
  my-react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9876:3000"
    volumes:
      - /app/node_modules
      - ./:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "test"]
